/// build.rs — Downloads the pdfium shared library at compile time for the
/// target platform, then generates `pdfium_embedded.rs` which embeds the
/// library bytes directly into the binary via `include_bytes!`.
///
/// This makes the final binary fully self-contained: no runtime dependency on
/// an installed pdfium is needed by the end user.
use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

/// Pinned pdfium chromium build number (from bblanchon/pdfium-binaries).
/// Update this when upgrading pdfium-render to keep symbols in sync.
const PDFIUM_VERSION: &str = "7881";

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let target_os = env::var("CARGO_CFG_TARGET_OS").expect("CARGO_CFG_TARGET_OS not set");
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").expect("CARGO_CFG_TARGET_ARCH not set");

    // Map target triple to bblanchon/pdfium-binaries platform string
    let platform = match (target_os.as_str(), target_arch.as_str()) {
        ("macos", "aarch64") => "mac-arm64",
        ("macos", "x86_64") => "mac-x64",
        ("linux", "x86_64") => "linux-x64",
        ("linux", "aarch64") => "linux-arm64",
        ("windows", "x86_64") => "win-x64",
        (os, arch) => panic!("Unsupported platform: {os}-{arch}. Add a mapping in build.rs."),
    };

    // Shared library name varies by OS
    let lib_name = match target_os.as_str() {
        "macos" => "libpdfium.dylib",
        "linux" => "libpdfium.so",
        "windows" => "pdfium.dll",
        os => panic!("Unsupported OS: {os}"),
    };

    let archive_path = format!("{out_dir}/pdfium.tgz");
    let extract_dir = format!("{out_dir}/pdfium_extracted");
    let lib_dest_path = format!("{out_dir}/{lib_name}");

    // Only download + extract if the library file is not already cached
    if !Path::new(&lib_dest_path).exists() {
        let url = format!(
            "https://github.com/bblanchon/pdfium-binaries/releases/download/chromium%2F{PDFIUM_VERSION}/pdfium-{platform}.tgz"
        );

        eprintln!("build.rs: downloading pdfium ({platform}) from {url}");

        // Download the archive using curl (available on macOS/Linux/Windows CI)
        let curl_status = Command::new("curl")
            .args(["-fsSL", "-o", &archive_path, &url])
            .status()
            .expect("build.rs: curl not found — please install curl");

        if !curl_status.success() {
            panic!("build.rs: failed to download pdfium from {url}");
        }

        // Extract the tgz archive
        fs::create_dir_all(&extract_dir).unwrap();
        let tar_status = Command::new("tar")
            .args(["-xzf", &archive_path, "-C", &extract_dir])
            .status()
            .expect("build.rs: tar not found");

        if !tar_status.success() {
            panic!("build.rs: failed to extract pdfium archive");
        }

        // Copy the library file to OUT_DIR root for easy referencing
        let extracted_lib = format!("{extract_dir}/lib/{lib_name}");
        fs::copy(&extracted_lib, &lib_dest_path)
            .unwrap_or_else(|e| panic!("build.rs: failed to copy {extracted_lib}: {e}"));
    }

    // Generate pdfium_embedded.rs with an include_bytes! pointing to the library.
    // The absolute path is used so include_bytes! works regardless of crate root.
    let generated_code = format!(
        "/// Auto-generated by build.rs. DO NOT EDIT.\n\
         /// Embedded pdfium library bytes for the current target platform.\n\
         pub const PDFIUM_LIB_BYTES: &[u8] = include_bytes!({lib_dest_path:?});\n\
         pub const PDFIUM_LIB_NAME: &str = {lib_name:?};\n"
    );

    let generated_path = format!("{out_dir}/pdfium_embedded.rs");
    fs::write(&generated_path, generated_code)
        .expect("build.rs: failed to write pdfium_embedded.rs");

    // Rebuild only if build.rs changes (not on every source change)
    println!("cargo:rerun-if-changed=build.rs");
}
